version: "3"

services:
    nextjs:
        container_name: nextjs
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        env_file:
            - .env
        command: "npm run dev"


volumes:
    node_modules:
