# docker-compose-server.yaml

version: "3"

services:
    server:
        container_name: blog-server
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
            - run_vol:/var/run
            - cache_vol:/var/cache
            - tmp_vol:/tmp
        env_file:
            - .env
        command: >
            sh -c "npm install && npx prisma generate && npm start"
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: mysecretpassword
        ports:
            - "5432:5432"
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    run_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
    cache_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
    tmp_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
